name: inforas
description: "Aplicacion InfoRas (Info Rasopatias) En flutter"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  form_field_validator: ^1.1.0
  get: ^4.6.6
  provider: ^6.1.2
  table_calendar: ^3.1.1
  flutter_secure_storage: ^9.0.0
  http: ^1.1.0
  intl: ^0.19.0
  syncfusion_flutter_calendar: ^25.2.5
  iconsax: ^0.0.8
   # File Picker and File reader
  file_picker: ^8.0.3
  open_file: ^3.3.2
  firebase_core: ^3.0.0
  firebase_storage: ^12.0.0
  url_launcher: ^6.3.0
  dio: ^5.4.3+1
  path_provider: ^2.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
