name: inforas
description: "Aplicacion InfoRas (Info Rasopatias) En flutter"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  form_field_validator: ^1.1.0
  get: ^4.6.6
  provider: ^6.1.2
  table_calendar: ^3.1.1
  flutter_secure_storage: ^9.0.0
  googleapis: ^13.1.0
  googleapis_auth: ^1.4.0
  http: ^1.1.0
  intl: ^0.19.0
  syncfusion_flutter_calendar: ^25.2.5
  iconsax: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
